// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: crud/crudoperations.proto

package crud

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=Author,proto3" json:"Author,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_crud_crudoperations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crud_crudoperations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_crud_crudoperations_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_crud_crudoperations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crud_crudoperations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_crud_crudoperations_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_crud_crudoperations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crud_crudoperations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_crud_crudoperations_proto_rawDescGZIP(), []int{2}
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_crud_crudoperations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crud_crudoperations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_crud_crudoperations_proto_rawDescGZIP(), []int{3}
}

func (x *ReadResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=Author,proto3" json:"Author,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_crud_crudoperations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_crud_crudoperations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_crud_crudoperations_proto_rawDescGZIP(), []int{4}
}

func (x *Post) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_crud_crudoperations_proto protoreflect.FileDescriptor

const file_crud_crudoperations_proto_rawDesc = "" +
	"\n" +
	"\x19crud/crudoperations.proto\x12\x04crud\"W\n" +
	"\rCreateRequest\x12\x14\n" +
	"\x05Title\x18\x01 \x01(\tR\x05Title\x12\x16\n" +
	"\x06Author\x18\x02 \x01(\tR\x06Author\x12\x18\n" +
	"\aContent\x18\x03 \x01(\tR\aContent\" \n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\"\r\n" +
	"\vReadRequest\"0\n" +
	"\fReadResponse\x12 \n" +
	"\x05posts\x18\x01 \x03(\v2\n" +
	".crud.PostR\x05posts\"^\n" +
	"\x04Post\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x16\n" +
	"\x06Author\x18\x03 \x01(\tR\x06Author\x12\x18\n" +
	"\aContent\x18\x04 \x01(\tR\aContent2r\n" +
	"\tOperation\x123\n" +
	"\x06Create\x12\x13.crud.CreateRequest\x1a\x14.crud.CreateResponse\x120\n" +
	"\aReadAll\x12\x11.crud.ReadRequest\x1a\x12.crud.ReadResponseB\x10Z\x0egrpc_crud/crudb\x06proto3"

var (
	file_crud_crudoperations_proto_rawDescOnce sync.Once
	file_crud_crudoperations_proto_rawDescData []byte
)

func file_crud_crudoperations_proto_rawDescGZIP() []byte {
	file_crud_crudoperations_proto_rawDescOnce.Do(func() {
		file_crud_crudoperations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crud_crudoperations_proto_rawDesc), len(file_crud_crudoperations_proto_rawDesc)))
	})
	return file_crud_crudoperations_proto_rawDescData
}

var file_crud_crudoperations_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_crud_crudoperations_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: crud.CreateRequest
	(*CreateResponse)(nil), // 1: crud.CreateResponse
	(*ReadRequest)(nil),    // 2: crud.ReadRequest
	(*ReadResponse)(nil),   // 3: crud.ReadResponse
	(*Post)(nil),           // 4: crud.Post
}
var file_crud_crudoperations_proto_depIdxs = []int32{
	4, // 0: crud.ReadResponse.posts:type_name -> crud.Post
	0, // 1: crud.Operation.Create:input_type -> crud.CreateRequest
	2, // 2: crud.Operation.ReadAll:input_type -> crud.ReadRequest
	1, // 3: crud.Operation.Create:output_type -> crud.CreateResponse
	3, // 4: crud.Operation.ReadAll:output_type -> crud.ReadResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_crud_crudoperations_proto_init() }
func file_crud_crudoperations_proto_init() {
	if File_crud_crudoperations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crud_crudoperations_proto_rawDesc), len(file_crud_crudoperations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crud_crudoperations_proto_goTypes,
		DependencyIndexes: file_crud_crudoperations_proto_depIdxs,
		MessageInfos:      file_crud_crudoperations_proto_msgTypes,
	}.Build()
	File_crud_crudoperations_proto = out.File
	file_crud_crudoperations_proto_goTypes = nil
	file_crud_crudoperations_proto_depIdxs = nil
}
