// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: chatapp/chatapp.proto

package crud

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUser      string                 `protobuf:"bytes,1,opt,name=FromUser,proto3" json:"FromUser,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_chatapp_chatapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chatapp_chatapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chatapp_chatapp_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetFromUser() string {
	if x != nil {
		return x.FromUser
	}
	return ""
}

func (x *ChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_chatapp_chatapp_proto protoreflect.FileDescriptor

const file_chatapp_chatapp_proto_rawDesc = "" +
	"\n" +
	"\x15chatapp/chatapp.proto\x12\achatapp\"C\n" +
	"\vChatMessage\x12\x1a\n" +
	"\bFromUser\x18\x01 \x01(\tR\bFromUser\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage2A\n" +
	"\aChatApp\x126\n" +
	"\x04Chat\x12\x14.chatapp.ChatMessage\x1a\x14.chatapp.ChatMessage(\x010\x01B\x10Z\x0egrpc_crud/crudb\x06proto3"

var (
	file_chatapp_chatapp_proto_rawDescOnce sync.Once
	file_chatapp_chatapp_proto_rawDescData []byte
)

func file_chatapp_chatapp_proto_rawDescGZIP() []byte {
	file_chatapp_chatapp_proto_rawDescOnce.Do(func() {
		file_chatapp_chatapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatapp_chatapp_proto_rawDesc), len(file_chatapp_chatapp_proto_rawDesc)))
	})
	return file_chatapp_chatapp_proto_rawDescData
}

var file_chatapp_chatapp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chatapp_chatapp_proto_goTypes = []any{
	(*ChatMessage)(nil), // 0: chatapp.ChatMessage
}
var file_chatapp_chatapp_proto_depIdxs = []int32{
	0, // 0: chatapp.ChatApp.Chat:input_type -> chatapp.ChatMessage
	0, // 1: chatapp.ChatApp.Chat:output_type -> chatapp.ChatMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chatapp_chatapp_proto_init() }
func file_chatapp_chatapp_proto_init() {
	if File_chatapp_chatapp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatapp_chatapp_proto_rawDesc), len(file_chatapp_chatapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatapp_chatapp_proto_goTypes,
		DependencyIndexes: file_chatapp_chatapp_proto_depIdxs,
		MessageInfos:      file_chatapp_chatapp_proto_msgTypes,
	}.Build()
	File_chatapp_chatapp_proto = out.File
	file_chatapp_chatapp_proto_goTypes = nil
	file_chatapp_chatapp_proto_depIdxs = nil
}
