// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pkg/proto/filetransfer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	mi := &file_pkg_proto_filetransfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_filetransfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_filetransfer_proto_rawDescGZIP(), []int{0}
}

func (x *FileUploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileUploadRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type FileUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadResponse) Reset() {
	*x = FileUploadResponse{}
	mi := &file_pkg_proto_filetransfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadResponse) ProtoMessage() {}

func (x *FileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_filetransfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadResponse.ProtoReflect.Descriptor instead.
func (*FileUploadResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_filetransfer_proto_rawDescGZIP(), []int{1}
}

func (x *FileUploadResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileUploadResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_pkg_proto_filetransfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_filetransfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_filetransfer_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_pkg_proto_filetransfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_filetransfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_filetransfer_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type MetaDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderPath    string                 `protobuf:"bytes,1,opt,name=folder_path,json=folderPath,proto3" json:"folder_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaDataRequest) Reset() {
	*x = MetaDataRequest{}
	mi := &file_pkg_proto_filetransfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaDataRequest) ProtoMessage() {}

func (x *MetaDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_filetransfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaDataRequest.ProtoReflect.Descriptor instead.
func (*MetaDataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_filetransfer_proto_rawDescGZIP(), []int{4}
}

func (x *MetaDataRequest) GetFolderPath() string {
	if x != nil {
		return x.FolderPath
	}
	return ""
}

type MetaData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FileName         string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Size             int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ModificationTime string                 `protobuf:"bytes,3,opt,name=modification_time,json=modificationTime,proto3" json:"modification_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	mi := &file_pkg_proto_filetransfer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_filetransfer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_filetransfer_proto_rawDescGZIP(), []int{5}
}

func (x *MetaData) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MetaData) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MetaData) GetModificationTime() string {
	if x != nil {
		return x.ModificationTime
	}
	return ""
}

type MetaDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilesMetaData []*MetaData            `protobuf:"bytes,1,rep,name=filesMetaData,proto3" json:"filesMetaData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaDataResponse) Reset() {
	*x = MetaDataResponse{}
	mi := &file_pkg_proto_filetransfer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaDataResponse) ProtoMessage() {}

func (x *MetaDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_filetransfer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaDataResponse.ProtoReflect.Descriptor instead.
func (*MetaDataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_filetransfer_proto_rawDescGZIP(), []int{6}
}

func (x *MetaDataResponse) GetFilesMetaData() []*MetaData {
	if x != nil {
		return x.FilesMetaData
	}
	return nil
}

var File_pkg_proto_filetransfer_proto protoreflect.FileDescriptor

const file_pkg_proto_filetransfer_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/proto/filetransfer.proto\x12\x05proto\"F\n" +
	"\x11FileUploadRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\"E\n" +
	"\x12FileUploadResponse\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\".\n" +
	"\x0fDownloadRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\"(\n" +
	"\x10DownloadResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"2\n" +
	"\x0fMetaDataRequest\x12\x1f\n" +
	"\vfolder_path\x18\x01 \x01(\tR\n" +
	"folderPath\"h\n" +
	"\bMetaData\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12+\n" +
	"\x11modification_time\x18\x03 \x01(\tR\x10modificationTime\"I\n" +
	"\x10MetaDataResponse\x125\n" +
	"\rfilesMetaData\x18\x01 \x03(\v2\x0f.proto.MetaDataR\rfilesMetaData2\xcd\x01\n" +
	"\vFileService\x12?\n" +
	"\x06Upload\x12\x18.proto.FileUploadRequest\x1a\x19.proto.FileUploadResponse(\x01\x12=\n" +
	"\bDownload\x12\x16.proto.DownloadRequest\x1a\x17.proto.DownloadResponse0\x01\x12>\n" +
	"\vGetMetaData\x12\x16.proto.MetaDataRequest\x1a\x17.proto.MetaDataResponseB\x1dZ\x1bgRPC_filetransfer/pkg/protob\x06proto3"

var (
	file_pkg_proto_filetransfer_proto_rawDescOnce sync.Once
	file_pkg_proto_filetransfer_proto_rawDescData []byte
)

func file_pkg_proto_filetransfer_proto_rawDescGZIP() []byte {
	file_pkg_proto_filetransfer_proto_rawDescOnce.Do(func() {
		file_pkg_proto_filetransfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_filetransfer_proto_rawDesc), len(file_pkg_proto_filetransfer_proto_rawDesc)))
	})
	return file_pkg_proto_filetransfer_proto_rawDescData
}

var file_pkg_proto_filetransfer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_filetransfer_proto_goTypes = []any{
	(*FileUploadRequest)(nil),  // 0: proto.FileUploadRequest
	(*FileUploadResponse)(nil), // 1: proto.FileUploadResponse
	(*DownloadRequest)(nil),    // 2: proto.DownloadRequest
	(*DownloadResponse)(nil),   // 3: proto.DownloadResponse
	(*MetaDataRequest)(nil),    // 4: proto.MetaDataRequest
	(*MetaData)(nil),           // 5: proto.MetaData
	(*MetaDataResponse)(nil),   // 6: proto.MetaDataResponse
}
var file_pkg_proto_filetransfer_proto_depIdxs = []int32{
	5, // 0: proto.MetaDataResponse.filesMetaData:type_name -> proto.MetaData
	0, // 1: proto.FileService.Upload:input_type -> proto.FileUploadRequest
	2, // 2: proto.FileService.Download:input_type -> proto.DownloadRequest
	4, // 3: proto.FileService.GetMetaData:input_type -> proto.MetaDataRequest
	1, // 4: proto.FileService.Upload:output_type -> proto.FileUploadResponse
	3, // 5: proto.FileService.Download:output_type -> proto.DownloadResponse
	6, // 6: proto.FileService.GetMetaData:output_type -> proto.MetaDataResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_filetransfer_proto_init() }
func file_pkg_proto_filetransfer_proto_init() {
	if File_pkg_proto_filetransfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_filetransfer_proto_rawDesc), len(file_pkg_proto_filetransfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_filetransfer_proto_goTypes,
		DependencyIndexes: file_pkg_proto_filetransfer_proto_depIdxs,
		MessageInfos:      file_pkg_proto_filetransfer_proto_msgTypes,
	}.Build()
	File_pkg_proto_filetransfer_proto = out.File
	file_pkg_proto_filetransfer_proto_goTypes = nil
	file_pkg_proto_filetransfer_proto_depIdxs = nil
}
